name: Terraform AWS Destroy

on:
  workflow_dispatch: # Permitir ejecución manual desde GitHub
  push:
    branches:
      - destroy  # Se ejecutará automáticamente al hacer push en la rama 'destroy'

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar credenciales de AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: "us-east-1"

      # 3. Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # Inicializar Terraform
      - name: Initialize Terraform
        run: terraform init

      # Planifica la destrucción sacando el tfstate
      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan

      # Ejecutar el plan de destrucción
      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve tfplan